server:
  port: 8080
spring:
  profiles:
    active: production
  data:
    rest:
      base-path: /api

---
spring:
  profiles: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8
    pool-name: SpringBootHikariCP
    username: pc
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        format_sql: true

---
spring:
  profiles: production
  datasource:
     type: com.zaxxer.hikari.HikariDataSource
     pool-name: SpringBootHikariCP
     url: jdbc:postgresql://ec2-54-225-112-119.compute-1.amazonaws.com:5432/d7p4o0sth361vr
     username: csnwmmvbqupqfx
     password: Kg-lFNHr7BSWZB1ve9cT6rhc9j
     driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy