server:
  port: 8080
spring:
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#   url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8
    url: jdbc:postgresql://ec2-54-225-112-119.compute-1.amazonaws.com:5432/d7p4o0sth361vr
    pool-name: SpringBootHikariCP
    username: csnwmmvbqupqfx
    password: Kg-lFNHr7BSWZB1ve9cT6rhc9j
    driver-class-name: org.postgresql.Driver
  jpa:
#   database-platform: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /api
