server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=UTF-8
    pool-name: SpringBootHikariCP
    username: pc
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        format_sql: true
  data:
    rest:
      base-path: /api
